### ISSUE TITLE
IndexOutOfRangeException while copying a building plan

### ISSUE THREAD

**Issue by Hiestaa** [fezhub/DSP-Mods#1]
Hey and thanks for making this mod! Freaking awesome to scale the factory up without taking a click break every 5min!

I had this issue happening today which I think is related to this mod (see in the error message `DSP_Mods.CopyInserters.[...]`:
![image](https://user-images.githubusercontent.com/5394706/107586091-467d0c00-6bcd-11eb-8899-0292e0cc09e9.png)

I reproduced it a couple of time by placing enough solar panels in a row that I had the time to cancel the current building selection, then shift-copy one of the solar panels building plan (not the actual building, but the green ghost that's used as a placeholder until the bot places the building). 

I didn't notice any gameplay issue tho, but it's a bit annoying that it disables the auto-save. 

If I were to wager a guess, maybe the copied object doesn't exist in the `entityPool` just yet [over there](https://github.com/fezhub/DSP-Mods/blob/main/DSP_CopyInserters/CopyInserters.cs#L138)? Might just need to add an early `return` if the `objectid` is too large.

**Comment by Hiestaa** [comment]
Something [like that](https://github.com/fezhub/DSP-Mods/pull/2) maybe?

**Comment by cog-videogames** [comment]
I am able to reliably reproduce this when quickly placing several copies of a machine that has several sorters. For example, an assembler that has 3 input and 1 output that is copy-placed six times or so rapidly.

Slowing down a bit, by not placing copies so rapidly, seems to dodge the problem.

**Comment by Hiestaa** [comment]
I'll give it another try later today, but my experience yesterday was with solar panels (so no sorter). It also happened 100% of the time, no matter how quickly or slowly I copied the building plan (as long as it was still a building plan and not yet a completed building).

**Comment by kyldvs** [comment]
I believe there are two separate issues, the error with copying unbuilt buildings happens 100% of the time on copy (not when building). Then there is also an error when building several times quickly with a lot of inserters, but that error is sporadic.
