### ISSUE TITLE
Add optional key modifier to trigger copy with inserters

### ISSUE THREAD

**Issue by colin-daniels** [fezhub/DSP-Mods#15]
Could be nice to have an (optional) extra key modifier to trigger copy with inserters. For example, requiring Ctrl in addition to Shift + Click to trigger the copy. Could be a config-controllable option.

I think it would go a long way towards reassuring people who are nervous about the mod's stability if it's not going to always trigger on copy, plus sometimes it's nice to copy just the plain building.

**Comment by colin-daniels** [comment]
Would also fix things like #14 to an extent, though in that case belts could probably just be blacklisted.

**Comment by brokenmass** [comment]
I'm working pr to allow to toggle the pasting if the copied inserter by pressing ctrl (or some other key) after copying a building ( in a similar way on how advance build destruct riffles between build modes)

**Comment by colin-daniels** [comment]
Implemented in #11
