### ISSUE TITLE
Belt weirdness, when switching to belt construction after queued copy

### ISSUE THREAD

**Issue by colin-daniels** [fezhub/DSP-Mods#16]
Not really sure how to repro this one (tried and failed). I had just copied a bunch of assemblers and switched to finish some belts (red) and one belt went weird and connected from the area that was under construction w/ the copies (orange):
![image](https://user-images.githubusercontent.com/4268263/107865555-abd33600-6e35-11eb-8b8c-55b49e51bea2.png)

**Comment by fezhub** [comment]
I think I've seen this happen once without mods, might not be our fault?

**Comment by colin-daniels** [comment]
Yeah, not sure...since I haven't been able to reproduce the issue I'll just go ahead and close this.
