### ISSUE TITLE
Collision warnings with AdvancedBuildDestruct and inter-building sorters

### ISSUE THREAD

**Issue by colin-daniels** [fezhub/DSP-Mods#22]
Placed left to right, the collision warnings follow the cursor (due to a distance check I'd guess).
![image](https://user-images.githubusercontent.com/4268263/108139007-1d58f180-708d-11eb-858e-af3efcccd6b4.png)

I can take a look at this weekend if nobody else picks this up before then.

**Comment by brokenmass** [comment]
this most likely can fixed by calculating the exact position the inserter should end/start when calculating the collision using the same code of `AfterPrebuild_Postfix`

**Comment by brokenmass** [comment]
should be fixed by #29
