### ISSUE TITLE
Sorters kept past current build order

### ISSUE THREAD

**Issue by MunWolf** [fezhub/DSP-Mods#24]
Reproduction Steps:
Copy some building with sorters on them (for example furnaces)
Right click to cancel the build
Go to the building on the building bar
Observe the sorters exist on the building.

Note:
If you hit anything else in the build bar before going to the same building as you copied the sorters are cleared.

**Comment by cdeath-zz** [comment]
I was just about to post this same issue.  Verified exists with version 1.5.0.  This confused me the first time it happened, then I canceled construction completely and that cleared it up.
Amazing mod btw, thanks for this!

**Comment by kyldvs** [comment]
Rather than cancelling and going to the building again now you can just hit "tab" to change modes so that inserters aren't copied anymore

**Comment by cdeath-zz** [comment]
Well sure I suppose there are ways to get around this, but I think the point is that it does not function as expected.
My expectation of canceling a copied building with sorters and then selecting it from the build menu would be that the building no longer has sorters attached to it.

**Comment by kyldvs** [comment]
No disagreements, just providing an alternative in the meantime :)
