### ISSUE TITLE
Sorter direction pointing wrong way

### ISSUE THREAD

**Issue by guyinacube** [fezhub/DSP-Mods#27]
DSP version: 0.6.16.5780
Mod Version: 1.4

![Sorter direction wrong](https://user-images.githubusercontent.com/14206359/108599607-c6d30800-7357-11eb-95bf-2d28efd8bd50.png)

Copying a smelter has the sorters going the wrong way. When trying to place them where they line up, the sorters don't work.

**Comment by kyldvs** [comment]
When you copy something it will always start at the "default" orientation for the building. If you rotated a building when you placed it, then you copy it, you will have to perform those rotations again.

For example, if I build this smelter:

![image](https://user-images.githubusercontent.com/1830497/108600870-4d82e780-734e-11eb-9612-6a58af49937c.png)

Copy and rotate it:

![image](https://user-images.githubusercontent.com/1830497/108600881-61c6e480-734e-11eb-9f04-83ffdb16031f.png)


It's expected that when you copy the top one it has the original orientation of the (non-rotated) smelter:

![image](https://user-images.githubusercontent.com/1830497/108600896-7acf9580-734e-11eb-8a68-28c3ab6830ce.png)


This behavior is more apparent when you copy buildings that are not symmetrical:

![image](https://user-images.githubusercontent.com/1830497/108600915-9c308180-734e-11eb-9560-a2c8a60e9603.png)

**Comment by brokenmass** [comment]
this is casued by how the game treats the smelters and it has been fixed by #25 (but not released yet)
