### ISSUE TITLE
Needs foundation support bug

### ISSUE THREAD

**Issue by Malachosa** [fezhub/DSP-Mods#32]
I've tried this with the following versions 1.2.0 through 1.6.0
I am now getting a "needs foundation support" when CopyInserters is installed regardless of which building I'm trying to place.
Curiously 1.1.0 works, but of course doesn't have the preview features and has issues with sorter placement.

I've removed every other addon, running with just CopyInserters 1.6.0 and DSP 0.6.16.5780

**Comment by Malachosa** [comment]
Okay, I've done a tonne of debugging, and I believe this is actually an inter-mod problem and is likely a bug in the latest version of Touhma_GalacticScale by Touhma v1.1.2 (or possibly earlier), as when I have both that and CopyInserters 1.6.0, I get lots of issues with placing sorters (warning too close issues when there shouldn't be) or placing buildings (no foundation support)

And yet, when I downgrade to Touhma_GalacticScale v1.0.1 (a VERY early version) and stay with CopyInserters 1.6.0, these bugs go away.

So it's definitely an issue with Touhma_GalacticScale by Touhma v1.1.2 (or earlier).  I'll do some more testing to see which version starts to cause the issue and let Touhma know about this interaction.

**Comment by guyinacube** [comment]
You indicated that CopyInserters 1.6 gave you the error after you removed all addons. Or did you still have Touhma_GalacticScale present when doing the testing?

**Comment by Malachosa** [comment]
I still had Touhma_GalacticScale, so I believe it was not a bug in
CopyInserters, but rather a bug with the Touhma_GalacticScale mod
