### ISSUE TITLE
Unity Error when building is copied

### ISSUE THREAD

**Issue by Baldie-dev** [fezhub/DSP-Mods#35]
I am getting this error in version DSP 0.6.16.5780:

[Error  : Unity Log] MissingMethodException: Method not found: 'HarmonyLib.CodeInstruction.StoreField'.
Stack trace:
DSP_Mods.CopyInserters.PlayerAction_Build_Patch.CalculatePose (PlayerAction_Build,int,int) <0x0001b>
DSP_Mods.CopyInserters.PlayerAction_Build_Patch.SetCopyInfo_Postfix (PlayerAction_Build,PlanetFactory,PlanetAuxData,int,int) <0x012d5>
(wrapper dynamic-method) PlayerAction_Build.DMD<PlayerAction_Build..SetCopyInfo> (PlayerAction_Build,int,int) <0x00507>
PlayerAction_Inspect.GameTick (long) <0x009c4>
PlayerController.GameTick (long) <0x0013f>
Player.GameTick (long) <0x0006c>
GameData.GameTick (long) <0x000fb>
GameMain.FixedUpdate () <0x0025f

**Comment by whl19910402** [comment]
The same error happened after the new update. Then I even can not copy the building.

**Comment by fezhub** [comment]
This error usually means something has gone wrong with the installation of the support files from BepInEx and Harmony.
Have you installed these manually or via the Thunderstore Mod Manager?

**Comment by 2785** [comment]
Getting the same error in the new patch, running beplnEx 5.4.5 and copyInserters 1.6.0 both installed with r2modman. No other mods enabled too 🤔

**Comment by 2785** [comment]
ugh... conflict with the new 0.6.17.5932 feature of mass upgrade / dismantle (?) maybe (?)

**Comment by fezhub** [comment]
Just released an update 1.7 to fix the issue with 5932, please try that

**Comment by 2785** [comment]
worked like a charm

**Comment by colbycheeze** [comment]
Do I have to manual install, not sure how long it will take to be added to the mod manager?

**Comment by kyldvs** [comment]
@colbycheeze I had to restart the mod manager in order for it to realize there was an update.

**Comment by colbycheeze** [comment]
> @colbycheeze I had to restart the mod manager in order for it to realize there was an update.

ah! Okay thanks, and yes this works. I was really sad when I logged in and everything was breaking, I was like NOOOOOO my free day is ruined! :P
