### ISSUE TITLE
0.6.17.5932后无法使用复制分拣器了

### ISSUE THREAD

**Issue by lsl9119** [fezhub/DSP-Mods#36]

**Comment by rfmitchem** [comment]
Can confirm the error is in https://github.com/fezhub/DSP-Mods/blob/48f133032f67db5b8fcfcb64e0d606db612f9929/DSP_CopyInserters/PlayerAction_Build_Patch.cs#L143 this "GetBuildingsInAreaNonAlloc"

**Comment by ezonius** [comment]
![image](https://user-images.githubusercontent.com/61872098/110949980-91607f80-8343-11eb-86fa-48d7a94bcef9.png)
