### ISSUE TITLE
SphereProgress: What do the numbers mean?

### ISSUE THREAD

**Issue by marclevin-ep** [fezhub/DSP-Mods#39]
Cell progress has 3 numbers, however I can't see any explanation of what they are? Apologies if this is obvious.

**Comment by Malachosa** [comment]
> Cell progress has 3 numbers, however I can't see any explanation of what they are? Apologies if this is obvious.

Okay, I THINK I can answer this for you.... there are 3 numbers yes, for each dyson sphere node.

1 set for structure points, 1 set for cell points

So, on a completed node, you might see something like this

structure point 190/0/190
cell point 4276/0/4276

On a node in progress you might see something like this

structure point 188/2/190
cell point 137/80/6492

The last number (in this case 190 and 6492) is how many structure and cell points are required to complete the node
The second to last number (the 2 and the 80) I believe are how many structure points and cell points are in transit (on the way to the node right now)
The first number is how many structure and cell points the node has already

A node that has not started yet will therefore look something like this
structure point 0/0/190
cell point 0/0/6492

Also, while building a dyson sphere, nodes won't get cells if they are not currently supporting a shell directly attached to the node.  Nodes also need a minimum percentage of structure points BEFORE they will start accepting cell points in the form of solar sails (I don't know what this percentage is).  It has been my experience however that your dyson sphere structure points finish WAY faster than your cell points, so definitely prioritize solar sail production over rocket production.

Now, the numbers that this mod adds are just a summary of those 2 sets of numbers for the entire dyson sphere in that system.
