### ISSUE TITLE
Doesn't work if 'Automatically move building target' has been manually disabled

### ISSUE THREAD

**Issue by IwakuraLain1984** [fezhub/DSP-Mods#6]
Is it just me or the game update made it invalid. I think I install it right cuz I found Copy Inserters in LogOutput.log.

**Comment by fezhub** [comment]
Do you have 'Automatically move building target' disabled in Gameplay settings?
(have to check while God mode is enabled)

**Comment by JANIS1289** [comment]
Then you enable 'Automatically move building target' it works on newest version on god mode

**Comment by IwakuraLain1984** [comment]
> Do you have 'Automatically move building target' disabled in Gameplay settings?
> (have to check while God mode is enabled)

Thanks! It works. Thank you for your mod, very helpful!

**Comment by IwakuraLain1984** [comment]
> Then you enable 'Automatically move building target' it works on newest version on god mode

It works, thank you!
