### ISSUE TITLE
Copying chained builds seems to break?

### ISSUE THREAD

**Issue by melwil** [fezhub/DSP-Mods#7]
Was attempting to make a steel smelting build.

1. Placed down 1+2+belts manually, with the sorters going through.
2. Copied 1, placed down 3, all good so far, but it couldn't place the sorter in the middle, of course.
3. Copied 2, placed down 4, that's when the **error occurred**. It did place the sorter between the smelters, though.
4. Copied 1, placed down 5. It put down the smelter and the sorter going in from the belt.
5. Copied 2, placed down 6. Again, the smelter and the output to belt is placed down, but the sorter going between the smelters is not placed now, despite both smelters being built.
6. Copied 1, placed down 7. The bots do not even build this smelter now.

Hope this makes it reproduce the error!

Note: I did try again in God mode in 0.6.16.5775 and made sure I had enabled "Automatically move building target". After I did that, the same error was produced at the same point as described above, but I could place further smelters, which means that smelter 7 from the screenshot did end up getting build this time. 

![image](https://user-images.githubusercontent.com/632466/107765117-9379f300-6d31-11eb-99d2-fbcd1a2700b8.png)
![image](https://user-images.githubusercontent.com/632466/107765130-9bd22e00-6d31-11eb-9200-7089043ff2aa.png)

**Comment by fezhub** [comment]
Perfect report mate, been struggling to reproduce this one, looking into it now!
